spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
#  security:
#    basic:
#      enabled: true
  datasource:
#    url: jdbc:postgresql://192.168.99.100:5432/sim
    url: jdbc:postgresql://10.5.0.8:5432/sim
    username: sim
    password: simproject
    driverClassName: org.postgresql.Driver
flyway:
  enabled: false
  url: ${spring.datasource.url}
  locations: classpath:db/postgres/migration
  schemas: rest
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
service:
#  yahooFin: http://192.168.99.100:8082
  yahooFin: http://10.5.0.6:8082
