version: '3'

services:
  yahoo-fin:
    build: ./yahooFin
    ports:
      - 8082:8082
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
  rest:
    build: ./rest
    ports:
      - 8080:8080
    links:
      - yahoo-fin
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
        #  gateway: 10.5.0.1

